/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getManufacturingSystemAccess().getAlternatives_23_1(), "rule__ManufacturingSystem__Alternatives_23_1");
			builder.put(grammarAccess.getManufacturingSystemElementAccess().getAlternatives(), "rule__ManufacturingSystemElement__Alternatives");
			builder.put(grammarAccess.getInputConditionAccess().getAlternatives(), "rule__InputCondition__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getBinaryTypeAccess().getAlternatives(), "rule__BinaryType__Alternatives");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup(), "rule__ManufacturingSystem__Group__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_7(), "rule__ManufacturingSystem__Group_7__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_12(), "rule__ManufacturingSystem__Group_12__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_16(), "rule__ManufacturingSystem__Group_16__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_21(), "rule__ManufacturingSystem__Group_21__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_21_3(), "rule__ManufacturingSystem__Group_21_3__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_22(), "rule__ManufacturingSystem__Group_22__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_22_2(), "rule__ManufacturingSystem__Group_22_2__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_23(), "rule__ManufacturingSystem__Group_23__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getGroup_23_1_1(), "rule__ManufacturingSystem__Group_23_1_1__0");
			builder.put(grammarAccess.getManufacturingSystemElement_ImplAccess().getGroup(), "rule__ManufacturingSystemElement_Impl__Group__0");
			builder.put(grammarAccess.getManufacturingSystemElement_ImplAccess().getGroup_4(), "rule__ManufacturingSystemElement_Impl__Group_4__0");
			builder.put(grammarAccess.getManufacturingSystemElement_ImplAccess().getGroup_4_3(), "rule__ManufacturingSystemElement_Impl__Group_4_3__0");
			builder.put(grammarAccess.getStoragePointAccess().getGroup(), "rule__StoragePoint__Group__0");
			builder.put(grammarAccess.getStoragePointAccess().getGroup_6(), "rule__StoragePoint__Group_6__0");
			builder.put(grammarAccess.getStoragePointAccess().getGroup_6_2(), "rule__StoragePoint__Group_6_2__0");
			builder.put(grammarAccess.getStoragePointAccess().getGroup_7(), "rule__StoragePoint__Group_7__0");
			builder.put(grammarAccess.getStoragePointAccess().getGroup_7_2(), "rule__StoragePoint__Group_7_2__0");
			builder.put(grammarAccess.getWorkPieceTypeAccess().getGroup(), "rule__WorkPieceType__Group__0");
			builder.put(grammarAccess.getWorkPieceAccess().getGroup(), "rule__WorkPiece__Group__0");
			builder.put(grammarAccess.getResponsibleAccess().getGroup(), "rule__Responsible__Group__0");
			builder.put(grammarAccess.getManufacturingStepAccess().getGroup(), "rule__ManufacturingStep__Group__0");
			builder.put(grammarAccess.getManufacturingStepAccess().getGroup_6(), "rule__ManufacturingStep__Group_6__0");
			builder.put(grammarAccess.getManufacturingStepAccess().getGroup_6_2(), "rule__ManufacturingStep__Group_6_2__0");
			builder.put(grammarAccess.getManufacturingStepAccess().getGroup_13(), "rule__ManufacturingStep__Group_13__0");
			builder.put(grammarAccess.getManufacturingStepAccess().getGroup_18(), "rule__ManufacturingStep__Group_18__0");
			builder.put(grammarAccess.getTransportStepAccess().getGroup(), "rule__TransportStep__Group__0");
			builder.put(grammarAccess.getTransportStepAccess().getGroup_6(), "rule__TransportStep__Group_6__0");
			builder.put(grammarAccess.getTransportStepAccess().getGroup_6_2(), "rule__TransportStep__Group_6_2__0");
			builder.put(grammarAccess.getTransportStepAccess().getGroup_13(), "rule__TransportStep__Group_13__0");
			builder.put(grammarAccess.getTransportStepAccess().getGroup_18(), "rule__TransportStep__Group_18__0");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getGroup(), "rule__QualityAssuranceStep__Group__0");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getGroup_6(), "rule__QualityAssuranceStep__Group_6__0");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getGroup_6_2(), "rule__QualityAssuranceStep__Group_6_2__0");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getGroup_13(), "rule__QualityAssuranceStep__Group_13__0");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getGroup_18(), "rule__QualityAssuranceStep__Group_18__0");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getGroup(), "rule__CompositeManufacturingStep__Group__0");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getGroup_6(), "rule__CompositeManufacturingStep__Group_6__0");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getGroup_6_2(), "rule__CompositeManufacturingStep__Group_6_2__0");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getGroup_13(), "rule__CompositeManufacturingStep__Group_13__0");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getGroup_18(), "rule__CompositeManufacturingStep__Group_18__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getInputCondition_ImplAccess().getGroup(), "rule__InputCondition_Impl__Group__0");
			builder.put(grammarAccess.getOutputDecisionAccess().getGroup(), "rule__OutputDecision__Group__0");
			builder.put(grammarAccess.getOutputDecisionAccess().getGroup_0(), "rule__OutputDecision__Group_0__0");
			builder.put(grammarAccess.getOutputDecisionAccess().getGroup_4(), "rule__OutputDecision__Group_4__0");
			builder.put(grammarAccess.getWorkPieceConditionAccess().getGroup(), "rule__WorkPieceCondition__Group__0");
			builder.put(grammarAccess.getBinaryConditionAccess().getGroup(), "rule__BinaryCondition__Group__0");
			builder.put(grammarAccess.getNegationAccess().getGroup(), "rule__Negation__Group__0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getNameAssignment_1(), "rule__ManufacturingSystem__NameAssignment_1");
			builder.put(grammarAccess.getManufacturingSystemAccess().getStartAssignment_6(), "rule__ManufacturingSystem__StartAssignment_6");
			builder.put(grammarAccess.getManufacturingSystemAccess().getStartAssignment_7_1(), "rule__ManufacturingSystem__StartAssignment_7_1");
			builder.put(grammarAccess.getManufacturingSystemAccess().getEndAssignment_11(), "rule__ManufacturingSystem__EndAssignment_11");
			builder.put(grammarAccess.getManufacturingSystemAccess().getEndAssignment_12_1(), "rule__ManufacturingSystem__EndAssignment_12_1");
			builder.put(grammarAccess.getManufacturingSystemAccess().getStaffAssignment_15(), "rule__ManufacturingSystem__StaffAssignment_15");
			builder.put(grammarAccess.getManufacturingSystemAccess().getStaffAssignment_16_1(), "rule__ManufacturingSystem__StaffAssignment_16_1");
			builder.put(grammarAccess.getManufacturingSystemAccess().getResponsibleAssignment_20(), "rule__ManufacturingSystem__ResponsibleAssignment_20");
			builder.put(grammarAccess.getManufacturingSystemAccess().getUsesAssignment_21_2(), "rule__ManufacturingSystem__UsesAssignment_21_2");
			builder.put(grammarAccess.getManufacturingSystemAccess().getUsesAssignment_21_3_1(), "rule__ManufacturingSystem__UsesAssignment_21_3_1");
			builder.put(grammarAccess.getManufacturingSystemAccess().getTransformsAssignment_22_1(), "rule__ManufacturingSystem__TransformsAssignment_22_1");
			builder.put(grammarAccess.getManufacturingSystemAccess().getTransformsAssignment_22_2_1(), "rule__ManufacturingSystem__TransformsAssignment_22_2_1");
			builder.put(grammarAccess.getManufacturingSystemAccess().getConsistsOfAssignment_23_1_0(), "rule__ManufacturingSystem__ConsistsOfAssignment_23_1_0");
			builder.put(grammarAccess.getManufacturingSystemAccess().getConsistsOfAssignment_23_1_1_1(), "rule__ManufacturingSystem__ConsistsOfAssignment_23_1_1_1");
			builder.put(grammarAccess.getManufacturingSystemElement_ImplAccess().getNameAssignment_2(), "rule__ManufacturingSystemElement_Impl__NameAssignment_2");
			builder.put(grammarAccess.getManufacturingSystemElement_ImplAccess().getTransitionAssignment_4_2(), "rule__ManufacturingSystemElement_Impl__TransitionAssignment_4_2");
			builder.put(grammarAccess.getManufacturingSystemElement_ImplAccess().getTransitionAssignment_4_3_1(), "rule__ManufacturingSystemElement_Impl__TransitionAssignment_4_3_1");
			builder.put(grammarAccess.getManufacturingSystemElement_ImplAccess().getResponsibleAssignment_7(), "rule__ManufacturingSystemElement_Impl__ResponsibleAssignment_7");
			builder.put(grammarAccess.getStoragePointAccess().getNameAssignment_1(), "rule__StoragePoint__NameAssignment_1");
			builder.put(grammarAccess.getStoragePointAccess().getResponsibleAssignment_5(), "rule__StoragePoint__ResponsibleAssignment_5");
			builder.put(grammarAccess.getStoragePointAccess().getStoresAssignment_6_1(), "rule__StoragePoint__StoresAssignment_6_1");
			builder.put(grammarAccess.getStoragePointAccess().getStoresAssignment_6_2_1(), "rule__StoragePoint__StoresAssignment_6_2_1");
			builder.put(grammarAccess.getStoragePointAccess().getTransitionAssignment_7_1(), "rule__StoragePoint__TransitionAssignment_7_1");
			builder.put(grammarAccess.getStoragePointAccess().getTransitionAssignment_7_2_1(), "rule__StoragePoint__TransitionAssignment_7_2_1");
			builder.put(grammarAccess.getWorkPieceTypeAccess().getNameAssignment_1(), "rule__WorkPieceType__NameAssignment_1");
			builder.put(grammarAccess.getWorkPieceAccess().getHasTypeAssignment_4(), "rule__WorkPiece__HasTypeAssignment_4");
			builder.put(grammarAccess.getResponsibleAccess().getNameAssignment_1(), "rule__Responsible__NameAssignment_1");
			builder.put(grammarAccess.getManufacturingStepAccess().getNameAssignment_1(), "rule__ManufacturingStep__NameAssignment_1");
			builder.put(grammarAccess.getManufacturingStepAccess().getSpeedAssignment_5(), "rule__ManufacturingStep__SpeedAssignment_5");
			builder.put(grammarAccess.getManufacturingStepAccess().getTransitionAssignment_6_1(), "rule__ManufacturingStep__TransitionAssignment_6_1");
			builder.put(grammarAccess.getManufacturingStepAccess().getTransitionAssignment_6_2_1(), "rule__ManufacturingStep__TransitionAssignment_6_2_1");
			builder.put(grammarAccess.getManufacturingStepAccess().getResponsibleAssignment_9(), "rule__ManufacturingStep__ResponsibleAssignment_9");
			builder.put(grammarAccess.getManufacturingStepAccess().getInputAssignment_12(), "rule__ManufacturingStep__InputAssignment_12");
			builder.put(grammarAccess.getManufacturingStepAccess().getInputAssignment_13_1(), "rule__ManufacturingStep__InputAssignment_13_1");
			builder.put(grammarAccess.getManufacturingStepAccess().getOutputAssignment_17(), "rule__ManufacturingStep__OutputAssignment_17");
			builder.put(grammarAccess.getManufacturingStepAccess().getOutputAssignment_18_1(), "rule__ManufacturingStep__OutputAssignment_18_1");
			builder.put(grammarAccess.getTransportStepAccess().getNameAssignment_1(), "rule__TransportStep__NameAssignment_1");
			builder.put(grammarAccess.getTransportStepAccess().getSpeedAssignment_5(), "rule__TransportStep__SpeedAssignment_5");
			builder.put(grammarAccess.getTransportStepAccess().getTransitionAssignment_6_1(), "rule__TransportStep__TransitionAssignment_6_1");
			builder.put(grammarAccess.getTransportStepAccess().getTransitionAssignment_6_2_1(), "rule__TransportStep__TransitionAssignment_6_2_1");
			builder.put(grammarAccess.getTransportStepAccess().getResponsibleAssignment_9(), "rule__TransportStep__ResponsibleAssignment_9");
			builder.put(grammarAccess.getTransportStepAccess().getInputAssignment_12(), "rule__TransportStep__InputAssignment_12");
			builder.put(grammarAccess.getTransportStepAccess().getInputAssignment_13_1(), "rule__TransportStep__InputAssignment_13_1");
			builder.put(grammarAccess.getTransportStepAccess().getOutputAssignment_17(), "rule__TransportStep__OutputAssignment_17");
			builder.put(grammarAccess.getTransportStepAccess().getOutputAssignment_18_1(), "rule__TransportStep__OutputAssignment_18_1");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getNameAssignment_1(), "rule__QualityAssuranceStep__NameAssignment_1");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getSpeedAssignment_5(), "rule__QualityAssuranceStep__SpeedAssignment_5");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getTransitionAssignment_6_1(), "rule__QualityAssuranceStep__TransitionAssignment_6_1");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getTransitionAssignment_6_2_1(), "rule__QualityAssuranceStep__TransitionAssignment_6_2_1");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getResponsibleAssignment_9(), "rule__QualityAssuranceStep__ResponsibleAssignment_9");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getInputAssignment_12(), "rule__QualityAssuranceStep__InputAssignment_12");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getInputAssignment_13_1(), "rule__QualityAssuranceStep__InputAssignment_13_1");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getOutputAssignment_17(), "rule__QualityAssuranceStep__OutputAssignment_17");
			builder.put(grammarAccess.getQualityAssuranceStepAccess().getOutputAssignment_18_1(), "rule__QualityAssuranceStep__OutputAssignment_18_1");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getNameAssignment_1(), "rule__CompositeManufacturingStep__NameAssignment_1");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getSpeedAssignment_5(), "rule__CompositeManufacturingStep__SpeedAssignment_5");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getTransitionAssignment_6_1(), "rule__CompositeManufacturingStep__TransitionAssignment_6_1");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getTransitionAssignment_6_2_1(), "rule__CompositeManufacturingStep__TransitionAssignment_6_2_1");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getResponsibleAssignment_9(), "rule__CompositeManufacturingStep__ResponsibleAssignment_9");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getInputAssignment_12(), "rule__CompositeManufacturingStep__InputAssignment_12");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getInputAssignment_13_1(), "rule__CompositeManufacturingStep__InputAssignment_13_1");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getOutputAssignment_17(), "rule__CompositeManufacturingStep__OutputAssignment_17");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getOutputAssignment_18_1(), "rule__CompositeManufacturingStep__OutputAssignment_18_1");
			builder.put(grammarAccess.getCompositeManufacturingStepAccess().getContainsAssignment_21(), "rule__CompositeManufacturingStep__ContainsAssignment_21");
			builder.put(grammarAccess.getInputCondition_ImplAccess().getNameAssignment_2(), "rule__InputCondition_Impl__NameAssignment_2");
			builder.put(grammarAccess.getOutputDecisionAccess().getOutputTypesAssignment_0_2(), "rule__OutputDecision__OutputTypesAssignment_0_2");
			builder.put(grammarAccess.getOutputDecisionAccess().getInputAssignment_3(), "rule__OutputDecision__InputAssignment_3");
			builder.put(grammarAccess.getOutputDecisionAccess().getInputAssignment_4_1(), "rule__OutputDecision__InputAssignment_4_1");
			builder.put(grammarAccess.getWorkPieceConditionAccess().getNameAssignment_0(), "rule__WorkPieceCondition__NameAssignment_0");
			builder.put(grammarAccess.getWorkPieceConditionAccess().getRequiresTypeAssignment_4(), "rule__WorkPieceCondition__RequiresTypeAssignment_4");
			builder.put(grammarAccess.getBinaryConditionAccess().getNameAssignment_1(), "rule__BinaryCondition__NameAssignment_1");
			builder.put(grammarAccess.getBinaryConditionAccess().getLeftAssignment_4(), "rule__BinaryCondition__LeftAssignment_4");
			builder.put(grammarAccess.getBinaryConditionAccess().getTypeAssignment_5(), "rule__BinaryCondition__TypeAssignment_5");
			builder.put(grammarAccess.getBinaryConditionAccess().getRightAssignment_7(), "rule__BinaryCondition__RightAssignment_7");
			builder.put(grammarAccess.getNegationAccess().getNameAssignment_1(), "rule__Negation__NameAssignment_1");
			builder.put(grammarAccess.getNegationAccess().getContainsAssignment_6(), "rule__Negation__ContainsAssignment_6");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
