/**
 *
 * $Id$
 */
package manufacturingSystem.validation;

import manufacturingSystem.ManufacturingSystemElement;
import manufacturingSystem.Responsible;
import manufacturingSystem.StoragePoint;
import manufacturingSystem.WorkPiece;
import manufacturingSystem.WorkPieceType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link manufacturingSystem.ManufacturingSystem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ManufacturingSystemValidator {
	boolean validate();

	boolean validateConsistsOf(EList<ManufacturingSystemElement> value);
	boolean validateStart(EList<StoragePoint> value);
	boolean validateEnd(EList<StoragePoint> value);
	boolean validateUses(EList<WorkPieceType> value);
	boolean validateTransforms(EList<WorkPiece> value);
	boolean validateName(String value);
	boolean validateResponsible(Responsible value);
	boolean validateStaff(EList<Responsible> value);
}
