/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MyDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_ManufacturingSystem_InitiateKeyword_23_0_a;
	protected AbstractElementAlias match_ManufacturingSystem_InitiateKeyword_23_0_p;
	protected AbstractElementAlias match_ManufacturingSystem___InitiateKeyword_23_0___LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2__q__a;
	protected AbstractElementAlias match_ManufacturingSystem___InitiateKeyword_23_0___LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2__q__p;
	protected AbstractElementAlias match_ManufacturingSystem___InitiateKeyword_23_0_a_LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2__a;
	protected AbstractElementAlias match_ManufacturingSystem___LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2_InitiateKeyword_23_0_p__a;
	protected AbstractElementAlias match_ManufacturingSystem___RightCurlyBracketKeyword_23_1_1_2_InitiateKeyword_23_0_p_LeftCurlyBracketKeyword_23_1_1_0__a;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MyDslGrammarAccess) access;
		match_ManufacturingSystem_InitiateKeyword_23_0_a = new TokenAlias(true, true, grammarAccess.getManufacturingSystemAccess().getInitiateKeyword_23_0());
		match_ManufacturingSystem_InitiateKeyword_23_0_p = new TokenAlias(true, false, grammarAccess.getManufacturingSystemAccess().getInitiateKeyword_23_0());
		match_ManufacturingSystem___InitiateKeyword_23_0___LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2__q__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getManufacturingSystemAccess().getInitiateKeyword_23_0()), new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getManufacturingSystemAccess().getLeftCurlyBracketKeyword_23_1_1_0()), new TokenAlias(false, false, grammarAccess.getManufacturingSystemAccess().getRightCurlyBracketKeyword_23_1_1_2())));
		match_ManufacturingSystem___InitiateKeyword_23_0___LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2__q__p = new GroupAlias(true, false, new TokenAlias(false, false, grammarAccess.getManufacturingSystemAccess().getInitiateKeyword_23_0()), new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getManufacturingSystemAccess().getLeftCurlyBracketKeyword_23_1_1_0()), new TokenAlias(false, false, grammarAccess.getManufacturingSystemAccess().getRightCurlyBracketKeyword_23_1_1_2())));
		match_ManufacturingSystem___InitiateKeyword_23_0_a_LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2__a = new GroupAlias(true, true, new TokenAlias(true, true, grammarAccess.getManufacturingSystemAccess().getInitiateKeyword_23_0()), new TokenAlias(false, false, grammarAccess.getManufacturingSystemAccess().getLeftCurlyBracketKeyword_23_1_1_0()), new TokenAlias(false, false, grammarAccess.getManufacturingSystemAccess().getRightCurlyBracketKeyword_23_1_1_2()));
		match_ManufacturingSystem___LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2_InitiateKeyword_23_0_p__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getManufacturingSystemAccess().getLeftCurlyBracketKeyword_23_1_1_0()), new TokenAlias(false, false, grammarAccess.getManufacturingSystemAccess().getRightCurlyBracketKeyword_23_1_1_2()), new TokenAlias(true, false, grammarAccess.getManufacturingSystemAccess().getInitiateKeyword_23_0()));
		match_ManufacturingSystem___RightCurlyBracketKeyword_23_1_1_2_InitiateKeyword_23_0_p_LeftCurlyBracketKeyword_23_1_1_0__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getManufacturingSystemAccess().getRightCurlyBracketKeyword_23_1_1_2()), new TokenAlias(true, false, grammarAccess.getManufacturingSystemAccess().getInitiateKeyword_23_0()), new TokenAlias(false, false, grammarAccess.getManufacturingSystemAccess().getLeftCurlyBracketKeyword_23_1_1_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_ManufacturingSystem_InitiateKeyword_23_0_a.equals(syntax))
				emit_ManufacturingSystem_InitiateKeyword_23_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ManufacturingSystem_InitiateKeyword_23_0_p.equals(syntax))
				emit_ManufacturingSystem_InitiateKeyword_23_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ManufacturingSystem___InitiateKeyword_23_0___LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2__q__a.equals(syntax))
				emit_ManufacturingSystem___InitiateKeyword_23_0___LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2__q__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ManufacturingSystem___InitiateKeyword_23_0___LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2__q__p.equals(syntax))
				emit_ManufacturingSystem___InitiateKeyword_23_0___LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2__q__p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ManufacturingSystem___InitiateKeyword_23_0_a_LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2__a.equals(syntax))
				emit_ManufacturingSystem___InitiateKeyword_23_0_a_LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ManufacturingSystem___LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2_InitiateKeyword_23_0_p__a.equals(syntax))
				emit_ManufacturingSystem___LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2_InitiateKeyword_23_0_p__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ManufacturingSystem___RightCurlyBracketKeyword_23_1_1_2_InitiateKeyword_23_0_p_LeftCurlyBracketKeyword_23_1_1_0__a.equals(syntax))
				emit_ManufacturingSystem___RightCurlyBracketKeyword_23_1_1_2_InitiateKeyword_23_0_p_LeftCurlyBracketKeyword_23_1_1_0__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'initiate'*
	 *
	 * This ambiguous syntax occurs at:
	 *     consistsOf+=ManufacturingSystemElement '}' ((ambiguity) '{' '}')* (ambiguity) '}' (rule end)
	 */
	protected void emit_ManufacturingSystem_InitiateKeyword_23_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'initiate'+
	 *
	 * This ambiguous syntax occurs at:
	 *     consistsOf+=ManufacturingSystemElement '}' (ambiguity) ('{' '}' (ambiguity))* consistsOf+=ManufacturingSystemElement
	 *     consistsOf+=ManufacturingSystemElement (ambiguity) '{' ('}' (ambiguity) '{')* consistsOf+=ManufacturingSystemElement
	 *     responsible=[Responsible|EString] (ambiguity) '{' ('}' (ambiguity) '{')* consistsOf+=ManufacturingSystemElement
	 *     transforms+=WorkPiece (ambiguity) '{' ('}' (ambiguity) '{')* consistsOf+=ManufacturingSystemElement
	 *     uses+=WorkPieceType (ambiguity) '{' ('}' (ambiguity) '{')* consistsOf+=ManufacturingSystemElement
	 */
	protected void emit_ManufacturingSystem_InitiateKeyword_23_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('initiate' ('{' '}')?)*
	 *
	 * This ambiguous syntax occurs at:
	 *     consistsOf+=ManufacturingSystemElement (ambiguity) '}' (rule end)
	 *     consistsOf+=ManufacturingSystemElement (ambiguity) consistsOf+=ManufacturingSystemElement
	 *     responsible=[Responsible|EString] (ambiguity) '}' (rule end)
	 *     transforms+=WorkPiece (ambiguity) '}' (rule end)
	 *     uses+=WorkPieceType (ambiguity) '}' (rule end)
	 */
	protected void emit_ManufacturingSystem___InitiateKeyword_23_0___LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2__q__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('initiate' ('{' '}')?)+
	 *
	 * This ambiguous syntax occurs at:
	 *     responsible=[Responsible|EString] (ambiguity) consistsOf+=ManufacturingSystemElement
	 *     transforms+=WorkPiece (ambiguity) consistsOf+=ManufacturingSystemElement
	 *     uses+=WorkPieceType (ambiguity) consistsOf+=ManufacturingSystemElement
	 */
	protected void emit_ManufacturingSystem___InitiateKeyword_23_0___LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2__q__p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('initiate'* '{' '}')*
	 *
	 * This ambiguous syntax occurs at:
	 *     consistsOf+=ManufacturingSystemElement '}' (ambiguity) 'initiate'* '}' (rule end)
	 */
	protected void emit_ManufacturingSystem___InitiateKeyword_23_0_a_LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}' 'initiate'+)*
	 *
	 * This ambiguous syntax occurs at:
	 *     consistsOf+=ManufacturingSystemElement '}' 'initiate'+ (ambiguity) consistsOf+=ManufacturingSystemElement
	 */
	protected void emit_ManufacturingSystem___LeftCurlyBracketKeyword_23_1_1_0_RightCurlyBracketKeyword_23_1_1_2_InitiateKeyword_23_0_p__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('}' 'initiate'+ '{')*
	 *
	 * This ambiguous syntax occurs at:
	 *     consistsOf+=ManufacturingSystemElement 'initiate'+ '{' (ambiguity) consistsOf+=ManufacturingSystemElement
	 *     consistsOf+=ManufacturingSystemElement (ambiguity) consistsOf+=ManufacturingSystemElement
	 *     responsible=[Responsible|EString] 'initiate'+ '{' (ambiguity) consistsOf+=ManufacturingSystemElement
	 *     transforms+=WorkPiece 'initiate'+ '{' (ambiguity) consistsOf+=ManufacturingSystemElement
	 *     uses+=WorkPieceType 'initiate'+ '{' (ambiguity) consistsOf+=ManufacturingSystemElement
	 */
	protected void emit_ManufacturingSystem___RightCurlyBracketKeyword_23_1_1_2_InitiateKeyword_23_0_p_LeftCurlyBracketKeyword_23_1_1_0__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
