/**
 *
 * $Id$
 */
package manufacturingSystem.validation;

import manufacturingSystem.ManufacturingStep;
import manufacturingSystem.QualityAssurance;
import manufacturingSystem.TransportSteps;

import manufacturingSystem.WorkPieces;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link manufacturingSystem.ManufacturingStep}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ManufacturingStepValidator {
	boolean validate();

	boolean validateTransportsteps(EList<TransportSteps> value);
	boolean validateQualityassurance(QualityAssurance value);
	boolean validateManufacturingSeps(EList<ManufacturingStep> value);
	boolean validateTransportWorkPieces(EList<TransportSteps> value);

	boolean validateOuputWorkpieces(EList<WorkPieces> value);

	boolean validateInputWorkpieces(EList<WorkPieces> value);
}
