/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl1.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mydsl1.ui.internal.Mydsl1Activator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Mydsl1Activator.getInstance().getInjector("org.xtext.example.mydsl1.MyDsl");
	}

}
